### PR TITLE
logo added and readme updated

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by anoff** [comment]
Awesome thanks!

**Comment by anoff** [comment]
Closes https://github.com/anoff/plantbuddy/issues/15

**Comment by reallinfo** [comment]
Can I ask for something? Do you want to add any license to the repo? 

https://help.github.com/en/articles/licensing-a-repository 

I'd appreciate it if you added a license. but it's not a problem if you don't.  Also, Feel free to contact me if you need any logo. Have a nice day!

**Comment by anoff** [comment]
Oh crap you're right. Sorry for pointing it out. Should be MIT, will fix it

**Comment by anoff** [comment]
added a [LICENSE](https://github.com/anoff/plantbuddy/blob/master/LICENSE) and corresponding entry in the README

**Comment by reallinfo** [comment]
Thanks, Have a nice day!

**Pull request merged**
